version: '1'
services:
  kafka:
    image: confluentinc/cp-kafka
    container_name: kafka
    hostname: kafka
    ports:
      - "9092:9092"
    networks:
      - kafkanet
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT'
      KAFKA_LISTENERS: 'INTERNAL://kafka:39093,CONTROLLER://kafka:29093,EXTERNAL://0.0.0.0:9092'
      KAFKA_ADVERTISED_LISTENERS: 'INTERNAL://kafka:39093,EXTERNAL://localhost:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'INTERNAL'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      CLUSTER_ID: 'ciWo7IWazngRchmPES6q5A=='
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-producer:
    build:
      context: ./kafka-producer
      dockerfile: Dockerfile
    hostname: kafka-producer
    container_name: kafka-producer
    networks:
      - kafkanet
    depends_on:
      - kafka
    ports:
      - "39091:39091"
      - "8080:8080"
    env_file: "./kafka-producer/src/main/java/org/example/env/configuration.env"

  kafka-consumer:
    build:
      context: ./kafka-consumer
      dockerfile: Dockerfile
    hostname: kafka-consumer
    container_name: kafka-consumer
    networks:
      - kafkanet
    depends_on:
      - kafka
    ports:
      - "39090:39090"
      - "8181:8181"
    env_file: "./kafka-consumer/src/main/java/org/example/env/configuration.env"

networks:
  kafkanet:
    name: kafkanet