apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-broker-map
data:
  KAFKA_NODE_ID: "1"
  KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
  KAFKA_LISTENERS: "INTERNAL://kafka:39093,CONTROLLER://kafka:29093,EXTERNAL://0.0.0.0:9092"
  KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:39093,EXTERNAL://localhost:9092"
  KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
  KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:29093"
  KAFKA_PROCESS_ROLES: "broker,controller"
  CLUSTER_ID: "ciWo7IWazngRchmPES6q5A=="
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"